### PR TITLE
Feature: Edit WebDAV credentials

### PR DESCRIPTION
**Pull request by phil1995**
The user now has the ability to edit their existing WebDAV credentials in the WebDAV account list, thus fixing #101.

Currently, the user still has to lock and unlock their vaults themselves that are affected by the WebDAV credentials update to be able to use the updated credentials. This should be fixed in a subsequent PR, as this behavior is identical for the credential update of all cloud providers.

### CODE REVIEW

**Review by tobihagemann — CHANGES_REQUESTED** [review]
I noticed the following issue: After editing a WebDAV connection, the account list does not update.

**Comment by phil1995** [comment]
> I noticed the following issue: After editing a WebDAV connection, the account list does not update.

Oh, I actually didn't notice that. That's because in the account list we only observe changes in the database and not in the keychain.  Should be fixed by 0324b335a364f817a72a1259a9a52a1c7bfef712.

**Review by tobihagemann — COMMENTED** [review]
You mentioned that a user has to lock/unlock their vault. I noticed that even this case doesn't work yet:

1. "Open Existing Vault" and then use the WebDAV connection (browse root directory).
2. Edit WebDAV connection.
3. "Open Existing Vault" and then use the edited WebDAV connection (browse root directory).

It still shows the root directory from the previous connection.

I suppose this is just the same issue as you've already mentioned and will be addressed in a separate PR?

**Comment by phil1995** [comment]
> You mentioned that a user has to lock/unlock their vault. I noticed that even this case doesn't work yet:
> 
> 1. "Open Existing Vault" and then use the WebDAV connection (browse root directory).
> 2. Edit WebDAV connection.
> 3. "Open Existing Vault" and then use the edited WebDAV connection (browse root directory).
> 
> It still shows the root directory from the previous connection.
> 
> I suppose this is just the same issue as you've already mentioned and will be addressed in a separate PR?

I just thought about it again and in the Main app invalidating should actually be trivial, so the problem should be fixed by 35c162bda78aa7a1ed3f71df141644b0bb2dfcf6.

**Pull request merged**
